import {
  LayoutDashboard,
  BookOpen,
  UserCheck,
  Bus,
  Calendar,
  MessageSquareWarning,
  Map as MapIcon,
  Bell,
  Users,
  GraduationCap,
  ClipboardList,
  ShieldAlert,
  Activity,
  Megaphone,
  Briefcase,
  Search,
  MapPin,
  CarFront
} from 'lucide-react';

export const roleNavigation = {
  STUDENT: [
    { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    { name: 'My Classes', href: '/dashboard/classes', icon: BookOpen },
    { name: 'Attendance', href: '/dashboard/attendance', icon: UserCheck },
    { name: 'Campus Bus', href: '/dashboard/bus', icon: Bus },
    { name: 'Available Rooms', href: '/dashboard/rooms', icon: Search },
    { name: 'Events', href: '/dashboard/events', icon: Calendar },
    { name: 'Complaints', href: '/dashboard/complaints', icon: MessageSquareWarning },
    { name: 'Lost & Found', href: '/dashboard/lost-found', icon: Briefcase },
    { name: 'Campus Map', href: '/dashboard/map', icon: MapIcon },
    { name: 'Notifications', href: '/dashboard/notifications', icon: Bell },
  ],
  TEACHER: [
    { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    { name: 'My Classes', href: '/dashboard/classes', icon: BookOpen },
    { name: 'Attendance', href: '/dashboard/attendance', icon: UserCheck },
    { name: 'Students', href: '/dashboard/students', icon: Users },
    { name: 'Assignments', href: '/dashboard/assignments', icon: ClipboardList },
    { name: 'Announcements', href: '/dashboard/announcements', icon: Megaphone },
    { name: 'Classroom Reservation', href: '/dashboard/reservations', icon: MapPin },
    { name: 'Schedule', href: '/dashboard/schedule', icon: Calendar },
    { name: 'Events', href: '/dashboard/events', icon: Calendar },
    { name: 'Notifications', href: '/dashboard/notifications', icon: Bell },
  ],
  SECURITY: [
    { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    { name: 'Visitors', href: '/dashboard/visitors', icon: Users },
    { name: 'QR Verification', href: '/dashboard/verification', icon: Search },
    { name: 'Parking', href: '/dashboard/parking', icon: CarFront },
    { name: 'Emergency Alerts', href: '/dashboard/emergencies', icon: ShieldAlert },
    { name: 'Campus Activity', href: '/dashboard/activity', icon: Activity },
    { name: 'Notifications', href: '/dashboard/notifications', icon: Bell },
  ],
  ADMIN: [
    { name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard },
    { name: 'Users', href: '/dashboard/users', icon: Users },
    { name: 'Academic', href: '/dashboard/academic', icon: GraduationCap },
    { name: 'Classrooms', href: '/dashboard/classrooms', icon: MapPin },
    { name: 'Transportation', href: '/dashboard/transportation', icon: Bus },
    { name: 'Parking', href: '/dashboard/parking', icon: CarFront },
    { name: 'Events', href: '/dashboard/events', icon: Calendar },
    { name: 'Visitors', href: '/dashboard/visitors', icon: Users },
    { name: 'Complaints', href: '/dashboard/complaints', icon: MessageSquareWarning },
    { name: 'Notices', href: '/dashboard/notices', icon: Megaphone },
    { name: 'Lost & Found', href: '/dashboard/lost-found', icon: Briefcase },
    { name: 'Analytics', href: '/dashboard/analytics', icon: Activity },
    { name: 'Campus Map', href: '/dashboard/map', icon: MapIcon },
  ]
};
